#!/usr/bin/env bash
set -x

echo 'echo "1" > /proc/sys/net/ipv4/ip_forward' >> /etc/rc.local

cat <<EOF >/etc/sysconfig/iptables
# Generated by iptables-save v1.4.7 on Wed May  7 13:12:15 2014
*mangle
:PREROUTING ACCEPT [1078615:92369572]
:INPUT ACCEPT [378:25285]
:FORWARD ACCEPT [1078237:92344287]
:OUTPUT ACCEPT [387:41157]
:POSTROUTING ACCEPT [1078480:92372752]
COMMIT
# Completed on Wed May  7 13:12:15 2014
# Generated by iptables-save v1.4.7 on Wed May  7 13:12:15 2014
*nat
:PREROUTING ACCEPT [6:394]
:POSTROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [3:207]
:snat - [0:0]
:web1 - [0:0]
:web2 - [0:0]
-A PREROUTING -m state --state NEW -m statistic --mode nth --every 2 -j web1
-A PREROUTING -m state --state NEW -m statistic --mode nth --every 1 -j web2
-A POSTROUTING -j snat
-A snat -j SNAT --to-source 192.168.50.2
-A web1 -j LOG --log-prefix "dnat-to-web1: " --log-level 6
-A web1 -p tcp -m tcp --dport 80 -j DNAT --to-destination 192.168.50.10:80
-A web2 -j LOG --log-prefix "dnat-to-web2: " --log-level 6
-A web2 -p tcp -m tcp --dport 80 -j DNAT --to-destination 192.168.50.20:80
COMMIT
# Completed on Wed May  7 13:12:15 2014
# Generated by iptables-save v1.4.7 on Wed May  7 13:12:15 2014
*filter
:INPUT ACCEPT [378:25285]
:FORWARD ACCEPT [1078237:92344287]
:OUTPUT ACCEPT [243:28465]
-A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j LOG --log-prefix "LOCAL_PORT_80: "
COMMIT
# Completed on Wed May  7 13:12:15 2014
EOF

chkconfig iptables on

reboot
exit 0
