#!/usr/bin/env bash
set -x

echo 'echo "1" > /proc/sys/net/ipv4/ip_forward' >> /etc/rc.local

cat <<EOF >/etc/sysconfig/iptables
# Generated by iptables-save v1.4.7 on Wed May  7 03:24:30 2014
*mangle
:PREROUTING ACCEPT [1309:140438]
:INPUT ACCEPT [1092:101701]
:FORWARD ACCEPT [217:38737]
:OUTPUT ACCEPT [963:88751]
:POSTROUTING ACCEPT [1140:122655]
COMMIT
# Completed on Wed May  7 03:24:30 2014
# Generated by iptables-save v1.4.7 on Wed May  7 03:24:30 2014
*nat
:PREROUTING ACCEPT [8:500]
:POSTROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [7:508]
:snat - [0:0]
:web1 - [0:0]
:web2 - [0:0]
-A PREROUTING -m state --state NEW -m statistic --mode nth --every 2 -j web1 
-A PREROUTING -m state --state NEW -m statistic --mode nth --every 2 --packet 1 -j web2 
-A POSTROUTING -j snat 
-A snat -j SNAT --to-source 192.168.50.2 
-A web1 -j LOG --log-prefix "dnat-to-web1: " --log-level 6 
-A web1 -p tcp -m tcp --dport 80 -j DNAT --to-destination 192.168.50.10:80 
-A web2 -j LOG --log-prefix "dnat-to-web2: " --log-level 6 
-A web2 -p tcp -m tcp --dport 80 -j DNAT --to-destination 192.168.50.20:80 
COMMIT
# Completed on Wed May  7 03:24:30 2014
# Generated by iptables-save v1.4.7 on Wed May  7 03:24:30 2014
*filter
:INPUT ACCEPT [1092:101701]
:FORWARD ACCEPT [217:38737]
:OUTPUT ACCEPT [923:83918]
COMMIT
EOF

chkconfig iptables on

reboot
exit 0
