VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :lb do |lb_config|
    lb_config.vm.box = "chef/centos-6.5"
    lb_config.vm.host_name = "lb"
    lb_config.vm.network "private_network", ip: "192.168.50.2"
    lb_config.vm.provision "shell", path: "script.sh"
  end

  (1..2).each do |i|
   config.vm.define "web-#{i}" do |slave|
     slave.vm.box = "chef/centos-6.5"
     slave.vm.host_name = "web-#{i}"
     slave.vm.network "private_network", ip: "192.168.50.#{i}0"
     slave.vm.provision "shell", path: "web.sh"
   end
  end

end
