VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :lb do |lb_config|
    lb_config.vm.box = "chef/centos-6.5"
    lb_config.vm.host_name = "lb"
    lb_config.vm.network "private_network", ip: "192.168.50.2"
    lb_config.vm.provision "shell", path: "script.sh"
  end
  config.vm.define :web1 do |web1_config|
    web1_config.vm.box = "chef/centos-6.5"
    web1_config.vm.host_name = "web1"
    web1_config.vm.network "private_network", ip: "192.168.50.20"
    web1_config.vm.provision "shell", path: "web.sh"
  end
  config.vm.define :web2 do |web2_config|
    web2_config.vm.box = "chef/centos-6.5"
    web2_config.vm.host_name = "web2"
    web2_config.vm.network "private_network", ip: "192.168.50.30"
    web2_config.vm.provision "shell", path: "web.sh"
  end
end
